### ISSUE TITLE
Itertools's `step_by()` has been implemented in `std::iter`

### ISSUE THREAD

**Issue by chawyehsu** [rustomax/rust-iterators#9]
https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.step_by
https://docs.rs/itertools/0.10.0/itertools/trait.Itertools.html#method.step

The following snippet should be removed or updated.
```
Remember how we used filter() to produce a range of even numbers? Itertools has a handy step_by() method for that.

extern crate itertools;
use itertools::Itertools;

for i in (0..11).step_by(2) {
    print!("{} ", i);
}

//output: 0 2 4 6 8 10
```

**Comment by rustomax** [comment]
Fixed in the latest commit. Thanks for the heads-up.
